FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD backend.jar /opt/backend/
EXPOSE 8080
WORKDIR /opt/backend/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "backend.jar"]
