import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavHeader from "@/components/headers/NavHeader/NavHeaderContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ZIDIO Connect",
  description: "Generated by Ansh Sharma",
    icons: {
    icon: "/favicon.ico",
    }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NavHeader />
      <main>
          {children}
      </main>
      </body>
    </html>
  );
}
