'use client'
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavHeader from "@/components/headers/NavHeader/NavHeaderContainer";
import {usePathname} from "next/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const metadata = {
    title: "ZIDIO Connect",
    description: "Generated by Ansh Sharma",
    icons: {
        icon: "/favicon.ico",
    }
};

export default function RootLayout({children}) {
    const pathname = usePathname();
    const showNavHeader = !pathname.startsWith("/auth");
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        { showNavHeader && <NavHeader />}
        <main>
            {children}
        </main>
        </body>
        </html>
    );
}
