package com.z_connect.common.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a skill in the system.
 * This class is an entity that maps to the "skills" table in the database.
 */
@Data
@Entity
@Table(name = "skills")
@NoArgsConstructor
@AllArgsConstructor
public class Skill {

    /**
     * The unique identifier for the skill.
     * It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the skill.
     * This column is unique, not nullable, and has a maximum length of 100 characters.
     */
    @Column(name = "skill_name", length = 100, nullable = false, unique = true)
    private String skill_name;

}
